#' This is the location function alias gps.
#' It utilizes a google API with key provided .
#' It gets the location of the user in terms of latitude and longitude.
#'
#' @return A list of latitude and of longitude
#' @import httr
#' @export
#'
#' @name gps
location <- function() {
  Google_Key <- "AIzaSyA-8CTDisLXo_SLzKRQMv7ds4porl_cq9Q"
  url <- paste0("https://www.googleapis.com/geolocation/v1/geolocate?key=", Google_Key)
  response <-httr::POST(url)
  print(response)


  if (httr::http_type(response) == "application/json") {
    success <- httr::content(response, "parsed")
    lat<-success$location$lat
    lng<-success$location$lng
  }
  return(c(lat,lng))
}
gps<- location()

#' This is the populate list function alias stations.
#' It utilizes the coordinates generated by the location function.
#' It gets data from the weather API and generate a dataframe with weather data
#'
#' @param gps (these are the coordinates from the location function)
#'
#' @return A data-frame with a minimum of twenty nearest weather stations according to user location .
#' Weather data from the weather stations generated.
#' @import httr
#' @import jsonlite
#' @export
#'
#' @name stations
PopulateList <- function(gps) {
  key <- "8c8a482f0c519bcc56bf79715ea71154"
  service_url <- "https://api.openweathermap.org/data/2.5/find?"

  url <- paste0(service_url, "appid=", key, "&lat=", gps[1], "&lon=", gps[2], "&cnt=20&units=metric")
  print(url)

  data <- httr::GET(url)

  if (httr::status_code(data) == 200) {
    datacontent <- httr::content(data, as = "text")
    dataJSON <- jsonlite::fromJSON(datacontent, simplifyVector = FALSE)

    result_list <- list()

    for (i in seq_along(dataJSON$list)) {
      city_id <- dataJSON$list[[i]]$id
      city_name <- dataJSON$list[[i]]$name
      coordinates <- dataJSON$list[[i]]$coord
      temperature <- dataJSON$list[[i]]$main$temp
      humidity <- dataJSON$list[[i]]$main$humidity


      result_df <- data.frame(city_id = city_id, city_name = city_name, latitude = coordinates$lat,
                              longitude = coordinates$lon, temperature = temperature, humidity = humidity)


      result_list[[i]] <- result_df
    }


    result_df <- do.call(rbind, result_list)

    print( result_df)

    return(result_df)
  } else {
    print("Error: Failed to retrieve data from the API.")
    return(NULL)
  }
}
stations <- PopulateList(gps)

#' This is the station maps function alias temptell.
#' It utilizes the returns from the stations and gps functions.
#' It creates a leaflet map with the weather stations and temperature data.
#'
#' @param stations these are the weather stations retreived from the weather API.
#' @param gps These are the latitude and longitude coordinates from the gps function .
#'  It uses the coordinates to set the view of the leaflet map .
#'  It creates the markers for the stations in the map using the same coordinates.
#'
#' @return A leaflet map
#'  Markers for the weather stations with temperature data.
#'  @import leaflet
#' @export
#'
#' @name temptell
stationMap <- function(stations,gps) {
  map <- leaflet::leaflet()
  map <- leaflet::addTiles(map)  # Add default OSM web map
  map <- leaflet::setView(map, lng = gps[2], lat = gps[1], zoom = 10)  # Set initial map view to the given coordinates


  for (i in seq_len(nrow(stations))) {
    city_name <- stations$city_name[i]
    coordinates <- c(stations$longitude[i], stations$latitude[i])
    temperature <- stations$temperature[i]

    popup_message <- paste("Station:", city_name, "<br>",
                           "Temperature:", temperature, "°C")

    map <- leaflet::addMarkers(map, lng = coordinates[1], lat = coordinates[2],
                               popup = popup_message)
  }

  print(map)

  return(map)
}
temptell <- stationMap(stations,gps)

